server:
  port: 17676
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql:///train_member?characterEncoding=UTF8&autoReconnect=true&serverTimeZone=Asia/Shanghai
    username: train_member
    password: train
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    cn.imqinhao.train.member.mapper: trace