POST http://localhost:20000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "memberId": "1689073542949376000",
  "name": "敖雯昕",
  "idCard": "360502200011074629",
  "type": "1"
}

###

GET http://localhost:20000/member/passenger/query-list?page=1&size=5
Accept: application/json
token: {{token}}

###

DELETE http://localhost:20000/member/passenger/delete/1689256528244248576
Accept: application/json
token: {{token}}