GET http://localhost:20000/member/member/count
Accept: application/json
token: 123

###
POST http://localhost:20000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=17364060319

###

POST http://localhost:20000/member/member/send-code
Content-Type: application/json

{
  "mobile": "13469810043"
}

###

POST http://localhost:20000/member/member/login
Content-Type: application/json

{
  "mobile": "15697204255",
  "code": "1314"
}

> {%
client.log(JSON.stringify(response.body))
client.log(JSON.stringify(response.body.content.token))
client.global.set("token", response.body.content.token)
 %}

###

