POST http://localhost:20000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "memberId": "1688860788032409600",
  "name": "覃曼",
  "idCard": "420528200005293526",
  "type": "1"
}
