server:
  port: 37676
  servlet:
    context-path: /business
spring:
  datasource:
    url: jdbc:mysql:///train_business?characterEncoding=UTF8&autoReconnect=true&serverTimeZone=Asia/Shanghai
    username: train_business
    password: train
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: business
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    cn.imqinhao.train.business.mapper: trace