server:
  port: 47676
  servlet:
    context-path: /batch
spring:
  datasource:
    url: jdbc:mysql:///train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimeZone=Asia/Shanghai
    username: train_batch
    password: train
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: batch
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    cn.imqinhao.train.member.mapper: trace